development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:a103569086498de6c2607cbd2b7a415c@tarpon.redistogo.com:10395/
  channel_prefix: message_me_production
